development:
  adapter: postgresql
  encoding: unicode
  database: busme_dev
  pool: 5
  username: rails
  password: railsyang

test:
  adapter: postgresql
  encoding: unicode
  database: busme_test
  pool: 5
  username: rails
  password: railsyang

production:
  adapter: postgresql
  encoding: unicode
  database: busme_production
  pool: 5
  username: rails
  password: railsyang